# Generated by Django 5.0.14 on 2025-06-08 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_CATEGORIA', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='NOMBRE_CATEGORIA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.IntegerField(db_column='ID_CIUDAD', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodosDePago',
            fields=[
                ('id_mp', models.IntegerField(db_column='ID_MP', primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(db_column='TIPO_PAGO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.IntegerField(db_column='ID_TIPO_USUARIO', primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(db_column='TIPO_USUARIO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(db_column='ID_COMUNA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('id_ciudad', models.ForeignKey(db_column='ID_CIUDAD', on_delete=django.db.models.deletion.CASCADE, to='core.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id_usuario', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('rut', models.CharField(db_column='RUT', max_length=20, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(db_column='APELLIDO', max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(db_column='EMAIL', max_length=100, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=200, null=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('is_staff', models.BooleanField(db_column='IS_STAFF', default=False)),
                ('is_superuser', models.BooleanField(db_column='IS_SUPERUSER', default=False)),
                ('last_login', models.DateTimeField(blank=True, db_column='LAST_LOGIN', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_comuna', models.ForeignKey(blank=True, db_column='ID_COMUNA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comuna', verbose_name='Comuna')),
                ('id_tipo_usuario', models.ForeignKey(blank=True, db_column='ID_TIPO_USUARIO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipousuario', verbose_name='Tipo de Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_PRODUCTO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=500, null=True)),
                ('stock', models.IntegerField(db_column='STOCK')),
                ('precio_unitario', models.DecimalField(db_column='PRECIO_UNITARIO', decimal_places=2, max_digits=10)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='ID_CATEGORIA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioValoracionProducto',
            fields=[
                ('id_comentario_valoracion', models.AutoField(db_column='ID_COMENTARIO_VALORACION', primary_key=True, serialize=False)),
                ('comentario', models.CharField(db_column='COMENTARIO', max_length=500)),
                ('valoracion', models.IntegerField(db_column='VALORACION')),
                ('fecha_comentario', models.DateTimeField(db_column='FECHA_COMENTARIO', default=django.utils.timezone.now)),
                ('id_usuario', models.ForeignKey(db_column='ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_producto', models.ForeignKey(db_column='ID_PRODUCTO', on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='ID_SERVICIO', primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(db_column='NOMBRE_SERVICIO', max_length=100)),
                ('descripcion_servicio', models.CharField(blank=True, db_column='DESCRIPCION_SERVICIO', max_length=500, null=True)),
                ('precio_servicio', models.DecimalField(db_column='PRECIO_SERVICIO', decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.IntegerField(blank=True, db_column='DURACION_MINUTOS', null=True)),
                ('disponible', models.CharField(db_column='DISPONIBLE', max_length=1)),
                ('id_proveedor_servicio', models.ForeignKey(db_column='ID_PROVEEDOR_SERVICIO', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaServicio',
            fields=[
                ('id_instancia_servicio', models.AutoField(db_column='ID_INSTANCIA_SERVICIO', primary_key=True, serialize=False)),
                ('fecha_hora_programada', models.DateTimeField(db_column='FECHA_HORA_PROGRAMADA')),
                ('reservado', models.CharField(db_column='RESERVADO', default='N', max_length=1)),
                ('estado_instancia', models.CharField(db_column='ESTADO_INSTANCIA', default='Programado', max_length=50)),
                ('id_proveedor_servicio', models.ForeignKey(blank=True, db_column='ID_PROVEEDOR_SERVICIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_servicio', models.ForeignKey(db_column='ID_SERVICIO', on_delete=django.db.models.deletion.DO_NOTHING, to='core.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id_venta_producto', models.AutoField(db_column='ID_VENTA_PRODUCTO', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(db_column='FECHA_VENTA', default=django.utils.timezone.now)),
                ('total_venta', models.DecimalField(db_column='TOTAL_VENTA', decimal_places=2, max_digits=10)),
                ('numero_seguimiento', models.CharField(blank=True, db_column='NUMERO_SEGUIMIENTO', max_length=100, null=True, unique=True)),
                ('transportista', models.CharField(blank=True, db_column='TRANSPORTISTA', max_length=50, null=True)),
                ('id_cliente', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_empleado', models.ForeignKey(blank=True, db_column='ID_EMPLEADO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventaproducto_empleado_set', to=settings.AUTH_USER_MODEL)),
                ('id_mp', models.ForeignKey(db_column='ID_MP', on_delete=django.db.models.deletion.DO_NOTHING, to='core.metodosdepago')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(db_column='ID_ENVIO', primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField(db_column='FECHA_ENVIO')),
                ('fecha_estimada_entrega', models.DateField(blank=True, db_column='FECHA_ESTIMADA_ENTREGA', null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, db_column='FECHA_ENTREGA_REAL', null=True)),
                ('estado_envio', models.CharField(db_column='ESTADO_ENVIO', max_length=50)),
                ('codigo_rastreo', models.CharField(blank=True, db_column='CODIGO_RASTREO', max_length=100, null=True, unique=True)),
                ('nombre_transportista', models.CharField(blank=True, db_column='NOMBRE_TRANSPORTISTA', max_length=100, null=True)),
                ('costo_envio', models.DecimalField(blank=True, db_column='COSTO_ENVIO', decimal_places=2, max_digits=10, null=True)),
                ('id_venta_producto', models.OneToOneField(db_column='ID_VENTA_PRODUCTO', on_delete=django.db.models.deletion.DO_NOTHING, related_name='envio_asociado', to='core.ventaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicioAdquirido',
            fields=[
                ('id_sa', models.AutoField(db_column='ID_SA', primary_key=True, serialize=False)),
                ('fecha_hora_adquisicion', models.DateTimeField(db_column='FECHA_HORA_ADQUISICION', default=django.utils.timezone.now)),
                ('precio_pagado', models.DecimalField(db_column='PRECIO_PAGADO', decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(db_column='ID_CLIENTE', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_instancia_servicio', models.ForeignKey(db_column='ID_INSTANCIA_SERVICIO', on_delete=django.db.models.deletion.DO_NOTHING, to='core.instanciaservicio')),
                ('id_mp', models.ForeignKey(db_column='ID_MP', on_delete=django.db.models.deletion.DO_NOTHING, to='core.metodosdepago')),
                ('id_venta_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ventaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_boleta', models.IntegerField(db_column='ID_DETALLE_BOLETA', primary_key=True, serialize=False)),
                ('cantidad_adquirida', models.IntegerField(db_column='CANTIDAD_ADQUIRIDA')),
                ('precio_venta_unitario', models.DecimalField(db_column='PRECIO_VENTA_UNITARIO', decimal_places=2, max_digits=10)),
                ('subtotal_detalle', models.DecimalField(db_column='SUBTOTAL_DETALLE', decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(db_column='ID_PRODUCTO', on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
                ('id_venta_producto', models.ForeignKey(db_column='ID_VENTA_PRODUCTO', on_delete=django.db.models.deletion.DO_NOTHING, to='core.ventaproducto')),
            ],
        ),
    ]
