# Generated by Django 5.2.1 on 2025-05-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComentarioValoracionProducto',
            fields=[
                ('id_comentario_valoracion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=500)),
                ('valoracion', models.BigIntegerField()),
                ('fecha_comentario', models.DateField()),
            ],
            options={
                'db_table': 'comentario_valoracion_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_boleta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad_adquirida', models.BigIntegerField()),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_detalle', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleServicioAdquirido',
            fields=[
                ('id_sa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_hora_adquisicion', models.DateField()),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_servicio_adquirido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('estado_envio', models.CharField(max_length=50)),
                ('codigo_rastreo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nombre_transportista', models.CharField(blank=True, max_length=100, null=True)),
                ('costo_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'envio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstanciaServicio',
            fields=[
                ('id_instancia_servicio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_hora_programada', models.DateField()),
                ('reservado', models.CharField(max_length=1)),
                ('estado_instancia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'instancia_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodosDePago',
            fields=[
                ('id_mp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'metodos_de_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('stock', models.BigIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('descripcion_servicio', models.CharField(blank=True, max_length=500, null=True)),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.BigIntegerField(blank=True, null=True)),
                ('disponible', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id_venta_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'venta_producto',
                'managed': False,
            },
        ),
    ]
